### ISSUE TITLE
Don't depend on external resources in test

### ISSUE THREAD

**Issue by lfaraone** [atmos/camo#103]
Currently, the test suite attempts to contact a number of sites during testing. Ideally, all these artifacts would be stored locally and DNS resolution mocked out to a local web server also started during test.

**Comment by atmos** [comment]
This app is essentially in maintenance mode and I'm not worried about these external deps. camo has been running for half a decade at GitHub so I think it's the type of thing that will be replaced before it's enhanced significantly.
