### ISSUE TITLE
Lots of "client request interrupted" recently from Camo

### ISSUE THREAD

**Issue by exogen** [atmos/camo#106]
I'm running [badge-matrix](https://github.com/exogen/badge-matrix) on Heroku and lately I've been getting a lot of H27 (client request interrupted) from Camo. Is the only reason Camo would close the connection due to `CAMO_SOCKET_TIMEOUT`? I don't think these requests are taking that long, so I want to make sure it isn't some other issue. (Does GitHub's deployment of Camo use the default timeout?)

You can also see the octopus GIF in Camo's own README is currently broken, but the real URL works fine in a browser. I don't know if the octopus is sad for the same reason my badges are failing, but it seems fishy to me (ba-dum tsss):

<img width="227" alt="screen shot 2016-07-27 at 10 57 31 am" src="https://cloud.githubusercontent.com/assets/53522/17186175/f24349e8-53e8-11e6-98e8-7a78c49ba442.png">

For me this is most noticeable on my [script-atomic-onload](https://github.com/exogen/script-atomic-onload) repo, which tests tons of JS script loaders and thus has dozens of badges – often the first 5 or so badge images will be broken due to Camo closing the connection early. This never seemed to happen months ago when I first released this repo, but it's very frequent now.

**Comment by atmos** [comment]
If you follow the octopus image you'll see this error, `Content length exceeded` GitHub may have tightened down the max size, but I have no clue how to tell. You'd have to ask support since I no longer work there.

Purging caches might help in debugging, https://help.github.com/articles/why-do-my-images-have-strange-urls/#removing-an-image-from-camos-cache

**Comment by exogen** [comment]
Oh good call, I didn't think to look at the broken image response body. Here's what I see when I fetch one of the broken badge images:

```sh
curl -i "https://camo.githubusercontent.com/5b0783f0d626fd04d15439e80bf469490695b81e/687474703a2f2f6261646765732e6865726f6b756170702e636f6d2f7472617669732f65786f67656e2f7363726970742d61746f6d69632d6f6e6c6f61643f6272616e63683d6d617374657226656e763d544553545f4c4f414445523d686561646a73266c6162656c3d486561644a53"
HTTP/1.1 504 Gateway Timeout
Cache-Control: no-cache, no-store, private, must-revalidate
Content-Security-Policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
Content-Type: text/plain; charset=utf-8
Server: github-camo (448b15a7)
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
X-GitHub-Request-Id: C71B4F20:5549:10BEFE8:579900C7
Content-Length: 24
Accept-Ranges: bytes
Date: Wed, 27 Jul 2016 18:43:24 GMT
Via: 1.1 varnish
Connection: keep-alive
X-Served-By: cache-lax1424-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1469645000.211335,VS0,VE4071
X-Fastly-Request-ID: f69a75f6886497cd3bd465bc9a096c7ff20341d7
Timing-Allow-Origin: https://github.com

Error Fetching Resource
```

Doing this again immediately returns the expected result (it's in the cache, but not sure if it's due to caching on my end or Camo's).

Looking at the Camo code, if `CAMO_SOCKET_TIMEOUT` is reached I'd expect a 404 with `Socket timeout` in the body. It looks like Varnish is sitting in front of Camo? Would that translate the 404 into a 504 Gateway Timeout? Hmmm...

Thanks for any help even though you're not with GitHub anymore! If 504 Gateway Timeout is their issue I'll try to hit up someone else.

**Comment by exogen** [comment]
I'm guessing GitHub has lowered their timeout to 5 sec, as timing the `camo.githubusercontent.com` shows:

```
real	0m5.000s
user	0m0.053s
sys	0m0.026s
```

And timing my badges directly shows:

```
real	0m4.969s
user	0m0.024s
sys	0m0.008s
```

So they're right on the threshold. 😭 

Guess I'll just have to make it faster somehow... closing this issue.
