### ISSUE TITLE
I think ALL travis-ci badges are broken on github!

### ISSUE THREAD

**Issue by a7madgamal** [atmos/camo#107]
when I add a badge like this one to readme.md files like this
`[![Build Status](https://travis-ci.org/Tickaroo/tikxml.svg?branch=master)](https://travis-ci.org/Tickaroo/tikxml)`

results this url: 
https://camo.githubusercontent.com/71f2cc1438ed37e52752b5a1724267b89fbb18ef/68747470733a2f2f7472617669732d63692e6f72672f5469636b61726f6f2f74696b786d6c2e7376673f6272616e63683d6d6173746572

which responds with "Error Fetching Resource" or "Cannot proxy the given URL"

I looked into different repos and they look the same
hope this can be fixed soon before people start fixing their files looking for solutions!

**Comment by rmm5t** [comment]
The internet is experiencing some gremlins this morning. There are outages across different services because of DNS issues. My guess is that what badges are experiencing is related. 

It's unrelated to this repository.

**Comment by Jeroen52** [comment]
Let's just try to embed the image into this thread.
![Build status](https://api.travis-ci.org/atmos/camo.svg?branch=master)

**Comment by Jeroen52** [comment]
Possibly this? https://www.reddit.com/r/sysadmin/comments/58ms8e/dyn_dns_under_ddos_attack/
