### ISSUE TITLE
Zupimages does not work

### ISSUE THREAD

**Issue by DarkZeroCD** [atmos/camo#110]
Hi!
The image host http://www.zupimages.net/ does not work.

**Comment by DarkZeroCD** [comment]
Same problem for http://www.noelshack.com/

**Comment by Jeroen52** [comment]
Both websites seem to work on my installation of Camo, did you copy the correct URL?

**Comment by atmos** [comment]
Hi,

I stopped working at GitHub about 2 years ago and the code is unchanged as far as I can tell. Since this has been in use since late 2010, the majority of users running into issues are suffering from two things.

1) Copying the URL incorrect
2) Misconfigured hosting providers

I'm not maintaining this applications anymore, nor do I have any ability to make changes to GitHub anymore.

**Comment by cactus** [comment]
There are also a few alternatives out there these days for people wanting to run their own instances:
https://github.com/willnorris/imageproxy
https://github.com/cactus/go-camo (nb: I made this one)

**Comment by Jeroen52** [comment]
@atmos Do you know anyone in GitHub that is maintaining Camo? Perhaps they have a closed source fork?

**Comment by DarkZeroCD** [comment]
@Jeroen52 For example this picture: http://zupimages.net/up/17/03/otqs.png
Did you change the code to make it work, or did it work when you installed it?

@atmos Okay, thanks for the information

@cactus A bit sad, camo seems to be very good and perfect at my setup.
I use a Debian and do not want to depend on Docker or Heroku, so successfully run go on my server I do not know?

**Comment by Jeroen52** [comment]
@DarkZeroCD It works on my installation.
I haven't modified any code, I am using Camo with the phpbb extension.

**Comment by DarkZeroCD** [comment]
@Jeroen52 I use FluxBB, so no modification exists, however with [this PHP code](https://github.com/atmos/camo/wiki/Generating-Signed-Image-URLs), it works very well except for Zupimages. 
I would try to make a comparison with the extension and find out how they managed to make it work more hosts.
