### ISSUE TITLE
Is there a way to detect 404?

### ISSUE THREAD

**Issue by tomav** [atmos/camo#116]
Hi guys, and thanks for this great project.
I was wondering if there are some event I can listen to update my backend when a saved URL is not valid anymore.

Any idea for that?

Thanks.

**Comment by rmm5t** [comment]
Idea: Turn on error logging with `CAMO_LOGGING_ENABLED=error` environment variable and pay attention to the 404 errors.

**Comment by tomav** [comment]
Thanks!
