### ISSUE TITLE
Does anyone else use this that could verify it? I don't run camo at my job anymore.

### ISSUE THREAD

**Issue by arjed555** [atmos/camo#145]
Does anyone else use this that could verify it? I don't run camo at my job anymore.

_Originally posted by @atmos in https://github.com/atmos/camo/pull/126#issuecomment-324126627_

**Comment by maznu** [comment]
Mattermost still recommends it: https://docs.mattermost.com/administration/image-proxy.html

**Comment by PeterDaveHello** [comment]
With all due respect, this project doesn't seem to be maintained anymore. It's using dated dependency which could have so many critical security issues.

Maybe @mattermost should consider to help maintain, or fork another project to continue its maintenance.

**Comment by atmos** [comment]
It totally isn't maintained anymore. It's 10 years old and I believe GitHub runs a modified version of https://github.com/cactus/go-camo these days.
