### ISSUE TITLE
how to work around this?

### ISSUE THREAD

**Issue by dominictarr** [atmos/camo#37]
I'm working on a service that has png badges that users can put in their git hub repos, https://feedopensource.com

Of course there are many other services which depend on this feature also.

The recent deployment of camo for https images has broken this service, however. So, I understand that setting `content-type: image/png` and `cache-control: no-cache` should make the proxy download a fresh image each time (the necessary behavior for badges to work)

However, since the URLs are cached there are many images which are hidden behind a cache but they should not be. Images like this are now stuck.

How can I get the badges to work again?
I can't figure out why my badge is 404ing

```
https://github-camo.global.ssl.fastly.net/73996164d000f0a65b18c888566e2ea469bf02fc/68747470733a2f2f666565646f70656e736f757263652e636f6d2f697465726174696f6e2f646f6d696e6963746172722f666565646f70656e736f757263652f31386f42455639684664444d45637439597332625341754559346269324b534d48692e706e673f727272727223312e32
```

```
https://feedopensource.com/iteration/dominictarr/feedopensource/18oBEV9hFdDMEct9Ys2bSAuEY4bi2KSMHi.png
```

I've tried adding `?blah` on the end to make a different url, which does produce a different hash, but I do not know why it's not displaying the image - which works if you open the image in a browser - curl doesn't have the right CA, so you need to use `--insecure`, but browsers do not complain.

there is no helpful messages in the camo headers, only "not found".

**Comment by atmos** [comment]
I'm closing this out unless people are still having problems. It's been 18+ months.
