### ISSUE TITLE
Preserve http_referer

### ISSUE THREAD

**Issue by saizai** [atmos/camo#43]
Compare:

```
curl -vvv https://makeyourlaws.org/travis-image -e https://github.com/rubysec/bundler-auDRFit/fafa3

Server sees:
x.x.x.x - - [03/Mar/2014:06:25:52 +0000] makeyourlaws.org "GET /travis-image HTTP/1.1" 302 154 "https://github.com/foo/bar/tree/baz/qux" "curl/7.35.0" "-"

Response:
< HTTP/1.1 302 Moved Temporarily
< Location: https://travis-ci.org/foo/bar.png?branch=baz
< Cache-Control: private
```

With what happens if an image link is put on a Github readme page:

```
Server sees:
x.x.x.x - - [03/Mar/2014:05:59:26 +0000] makeyourlaws.org "GET /travis-image HTTP/1.1" 404 162 "-" "Camo Asset Proxy 2.0.1" "-"
```

Because there's no http_referer or even x-forwarded-for, there's no way for me to serve the appropriate Travis CI image.

Please fix by preserving the http referer properly (and respecting cache-control private).

**Comment by coreymartella** [comment]
This is definitely a major annoyance. We want some auto badging on pull requests, branch pages, etc that is a snap todo with referrer info included within a private repo of a private organization. Are there any workarounds?

**Comment by atmos** [comment]
Sorry, I think the perspective here was that we value the privacy of our users more than hacks around them. Unfortunately I left github a few weeks back and wouldn't be able to make the change to their site anyway.

**Comment by saizai** [comment]
Surely there are ways to value privacy and preserve this?

All you need to do is preserve the _GitHub_ HTTP referer — either for
cached proxy requests or for direct ones. Doesn't need any other info to
work, but it does need to know the repo/branch it's being rendered on.

Sincerely,
- Sai

**Comment by atmos** [comment]
I'm sorry but this behavior isn't going away.
