### ISSUE TITLE
Can I override the proxy, to serve the original image URL?

### ISSUE THREAD

**Issue by dtrenz** [atmos/camo#57]
Is it possible to get the proxy service to leave an image URL alone - either via markdown or response header - so I can serve the image URL directly to the client, unmolested?

I'm trying to show a CI build status badge in my README.md but it's not loading the image. I'm guessing this is because the CI server that is hosting the build status badge image requires authentication, and the camo service isn't able to forward the auth/cookies of the client.

How can I get around this? 

Help appreciated.

**Comment by yaycmyk** [comment]
Seriously, why is this an issue? Let me add a query string param to just pass through camo if I want to...

**Comment by atmos** [comment]
@yaycmyk I should probably update the contributing.md file to indicate that I have no plans to enhance this application at all. It's almost 6 years old, it has proven its worth without this functionality, no one has asked for it in 2 years, and I no longer work at GitHub so you'd likely never see the feature on the site.

Sorry.
