### ISSUE TITLE
Heroku Deployment Error

### ISSUE THREAD

**Issue by matjones** [atmos/camo#66]
During deployment on Heroku, it fails with following:

Error: bash: bundle: command not found.

![fireshot screen capture 330 - create a new app i heroku - dashboard-next_heroku_com_new](https://cloud.githubusercontent.com/assets/92649/3911014/9093c4c8-231d-11e4-94be-ec4ce3eb0b48.jpg)

**Comment by md-5** [comment]
This can be closed :)
