### ISSUE TITLE
"Socket Timeout" Error after few hours

### ISSUE THREAD

**Issue by apavillet** [atmos/camo#72]
I'm sure this a not a bug from camo but few hours after starting the camo server and lots of urls proxied through, I start getting "socket timeout" and the images are not proxied anymore.

My guess is the system ran out of avalaible socket which are not "released" or "freed", did anyone had this kind of behaviour and managed to fix it ? Should we raise the file descriptor limit or any kind of linux limit ?

Thanks

**Comment by atmos** [comment]
I've seen that on older versions of camo that aren't closing sockets. I think we addressed this in #70 though.

**Comment by apavillet** [comment]
I'm up to date with camo says github :)

here's the exact error minus the urls :)

<code>
[2015-01-27T20:23:03.258Z] Socket timeout: http://image.jpg
[2015-01-27T20:23:03.259Z] Client Request error Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12): http://image.jpg
[2015-01-27T20:23:03.269Z] Socket timeout: http://image.jpg
[2015-01-27T20:23:03.270Z] Client Request error Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12): http://image.jpg

</code>

**Comment by atmos** [comment]
Is the process dying or are you just seeing errors in your logs?

**Comment by apavillet** [comment]
Well camo keeps running and i see this error for all proxied urls

**Comment by atmos** [comment]
Does it continue to proxy images?

**Comment by apavillet** [comment]
No :(

**Comment by apavillet** [comment]
I have to stop camo ans start it again

**Comment by atmos** [comment]
Are you running this on heroku? I don't see any of this behavior in our logs.

**Comment by apavillet** [comment]
No on a private server. Once again it could come from our conf

**Comment by atmos** [comment]
I'd double check the node version that you're running but I can't find similar behavior on our end. Maybe it's something with the images that you're proxying that are causing errors?

**Comment by apavillet** [comment]
The problem is gone. Problem is nothing has changed so I do not know why.

The only things I could think of is the difference in response from urls ( lots of hanging urls might not close the sockets ? ), just a guess.

Anyway thanks i'll close this one since it's not a problem for now !
