### ISSUE TITLE
Forward image when valid Content-Type & body

### ISSUE THREAD

**Issue by jomo** [atmos/camo#75]
Some services return a 404 or 5xx *with an image*. This can be used e.g. for default / fallback images and it's totally legitimate to do so.

I think camo should proxy **all valid images regardless of the HTTP status** – this is what Browsers do as well (or intend to, see [chromium-464515](https://code.google.com/p/chromium/issues/detail?id=464515)).

I'd be happy to make a PR if you agree.

**Comment by atmos** [comment]
I'd rather find someone to design a cool default image for [404 responses](https://github.com/atmos/camo/blob/master/server.coffee#L46-L57). Maybe we could have an environmentally configurable uri for 404,etc  response codes

**Comment by rmm5t** [comment]
@atmos I think @jomo's point was that some services already return a stock image along with 404 responses, and that it would be nice if camo truly proxied the body of 404 responses instead of short cutting to a 404 response with empty body.

**Comment by atmos** [comment]
Got it. Yeah, let's see what the changes look like and I'm open to applying it if the diff isn't super crazy. We rely on this pretty heavily and I'm always weary of accepting new changes these days. :smiley:
