### ISSUE TITLE
Request crashes camo

### ISSUE THREAD

**Issue by jhass** [atmos/camo#78]
I didn't catch the request causing it, but maybe the trace is enough.

```
Apr 17 06:36:23 aeshna.de node[266]: _http_outgoing.js:333
Apr 17 06:36:23 aeshna.de node[266]: throw new Error('"name" and "value" are required for setHeader().');
Apr 17 06:36:23 aeshna.de node[266]: ^
Apr 17 06:36:23 aeshna.de node[266]: Error: "name" and "value" are required for setHeader().
Apr 17 06:36:23 aeshna.de node[266]: at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
Apr 17 06:36:23 aeshna.de node[266]: at new ClientRequest (_http_client.js:101:14)
Apr 17 06:36:23 aeshna.de node[266]: at Object.exports.request (http.js:49:10)
Apr 17 06:36:23 aeshna.de node[266]: at Object.exports.get (http.js:53:21)
Apr 17 06:36:23 aeshna.de node[266]: at process_url (/usr/lib/camo/server.js:118:25)
Apr 17 06:36:23 aeshna.de node[266]: at Server.<anonymous> (/usr/lib/camo/server.js:301:18)
Apr 17 06:36:23 aeshna.de node[266]: at Server.emit (events.js:110:17)
Apr 17 06:36:23 aeshna.de node[266]: at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
Apr 17 06:36:23 aeshna.de node[266]: at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
Apr 17 06:36:23 aeshna.de node[266]: at Socket.socketOnData (_http_server.js:343:22)
```

Running 2.2.0.

**Comment by jhass** [comment]
Okay, this is actually happens for all requests so I reviewed recent configuration changes. I use Nginx as reverse proxy and switched `ssl on;` for `listen 443 ssl;`. I tried digging a bit into the docs as to what the difference could be that causes that, but to no avail. Maybe this helps reproducing the issue though.

**Comment by atmos** [comment]
What version of node? My hunch is that your reverse proxy is misconfigured though.

**Comment by jhass** [comment]
```
$ node -v
v0.12.2
```

```
  location /camo/ {
    proxy_redirect off;
    proxy_pass http://camo/;
    break; 
  }
...
upstream camo {
  server 127.0.0.1:9090;
}
```

**Comment by atmos** [comment]
Our production instance is running on 0.10.29 as indicated in the package.json file. Have you made any other modifications to the source?

**Comment by jhass** [comment]
I wrote myself a package: https://github.com/jhass/PKGBUILDs/tree/master/camo so just compiled again instead of using the committed .js file and appending a few mime types

**Comment by juergenhecht** [comment]
I had the same problem as @jhass. After changing the Arch Linux PKGBUILDs dependence on "nodejs" to "nodejs10", it works.

**Comment by atmos** [comment]
@jhass can you see if #84 fixed your problem?

**Comment by jhass** [comment]
I can actually no longer reproduce it, maybe a nodejs or nginx update fixed it. From my side feel free to close the issue.
