### ISSUE TITLE
Camo not compliant with RFC2046 on case insensitivity

### ISSUE THREAD

**Issue by kereyroper** [atmos/camo#79]
I saw this error in our logs:
Non-Image content-type returned 'image/JPEG'

The code doesn't appear to take case insensitivity of MIME Types into account.
https://github.com/atmos/camo/blob/7af31a0eda6d602111c857a007564a4f3f095185/server.coffee#L165

Nor does the mime-types.json, but I don't recommend adding all permutations of case there.

http://tools.ietf.org/html/rfc2046#section-4.2
4.2.  Image Media Type

   A media type of "image" indicates that the body contains an image.
   The subtype names the specific image format.  These names are not
   case sensitive. An initial subtype is "jpeg" for the JPEG format
   using JFIF encoding [JPEG]

**Comment by jlynn** [comment]
:+1:
