### ISSUE TITLE
Not following redirect?

### ISSUE THREAD

**Issue by thockin** [atmos/camo#88]
Document:  https://github.com/GoogleCloudPlatform/kubernetes/blob/3eca6871668a7b4eb6d2a1bc13875a175bc688dd/docs/README.md

The raw markdown is:  `![WARNING](http://releases.k8s.io/HEAD/docs/warning.png)`

Camo is rendering: https://camo.githubusercontent.com/19023af99ca9a2e65aea15804e54073a29f7ce53/687474703a2f2f72656c65617365732e6b38732e696f2f484541442f646f63732f7761726e696e672e706e67

That camo link is "not found".

```
$ curl -i http://releases.k8s.io/HEAD/docs/warning.png
HTTP/1.1 301 Moved Permanently
Server: nginx/1.2.1
Date: Wed, 15 Jul 2015 00:04:22 GMT
Content-Type: text/html
Content-Length: 184
Connection: keep-alive
Location: https://github.com/GoogleCloudPlatform/kubernetes/tree/HEAD/docs/warning.png

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.2.1</center>
</body>
</html>
```

I thought camo would follow redirects?

**Comment by atmos** [comment]
Camo does follow redirects. If you follow the redirects you'll see that it points to an html document and not an image. Camo doesn't proxy html documents.

**Comment by thockin** [comment]
doh, of course, how dumb of me.  Apologies
