### ISSUE TITLE
404 on GitHub stars/issues and Shields.io

### ISSUE THREAD

**Issue by ZiZuu-store** [atmos/camo#93]
![screen shot 2015-11-16 at 09 53 02](https://cloud.githubusercontent.com/assets/6018431/11177729/e179fc38-8c47-11e5-83a6-6dd2b2ed181c.png)

It seems that, very often but not always, images from [Shields.io](http://http://shields.io/) regarding GitHub *"live" scores* are giving **[404 error on Camo](https://camo.githubusercontent.com/d40fbc430c10ec9c01bc5101525f2619412a787e/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f646f776e6c6f6164732f61746f6d2f61746f6d2f6c61746573742f746f74616c2e7376673f7374796c653d706c6173746963)**.

- real life example: https://github.com/ZiZuu-store/zzCleanURLs/blob/dev/README.md
- as you can see in the above link non-live images do not rise the problem (the "chat" icon)

**Comment by atmos** [comment]
This has been discussed at length in other issues and loads of services work fine, there's something incorrect about their response headers if it's breaking. I would talk to the shields team.

Also, I no longer work at GitHub so I can't roll out any changes even if we did make them.

**Comment by ZiZuu-store** [comment]
Uhmm .. ok

It looks like a limit on number of requests .. will look how to report to both GitHub and Shields.io

Thanks
