### ISSUE TITLE
Images from flickr are not always displayed

### ISSUE THREAD

**Issue by matthieu-lapeyre** [atmos/camo#95]
Hi,

I have weird issue with the integration of GIF hosted on Flickr. 

On the readme, this gif works well:
https://github.com/matthieu-lapeyre/poppy-ergo-jr/blob/master/README.md

But on the assembly guide the others gif are not displayed:
https://github.com/matthieu-lapeyre/poppy-ergo-jr/blob/master/doc/assembly.md
with plenty of 404 error ...

here I have the same result:
![No bug](https://c1.staticflickr.com/1/770/23544569636_8854a6a510_o.gif)
![Bug](https://c1.staticflickr.com/1/681/22942875373_cf9efe94bf_o.gif)

Maybe it's a limit on the image size ?

**Comment by atmos** [comment]
It is, GitHub caps them at 5MB. Sorry.
